### ISSUE TITLE
End Command

### ISSUE THREAD

**Issue by RHaroldZ** [EverestWorks/EverTerm#3]
The "end" and "kill" command are buggy, and if you put end or kill and a letter between a-y, it would destroy your computer. I tested this on my linux vm and it the vm blacked out and restarted. (I'm afraid to test this on my windows computer)
For example, type "end a" or "kill y" and enter

**Comment by RHaroldZ** [comment]
Having invalid or no arguments in the commands: create, filelist, filecopy, startapp, and any custom commands will cause the terminal to exit out. My guess is that the invalid argument cause an error in the python code, and python errors will cause the terminal to shut down. As we see with custom mods, if there's an error in the python code the terminal wouldn't run. 
For example, if we filelist a non-existent directory, or not putting a directory, the terminal will exit out. Or if we put "create" and "startapp" by themselves w/o an argument, the terminal will exit out.  
![image](https://github.com/EverestWorks/EverTerm/assets/141180230/a33c850e-2665-4c86-be3c-cef4a4990003)

**Comment by MultiOSDev** [comment]
> Having invalid or no arguments in the commands: create, filelist, filecopy, startapp, and any custom commands will cause the terminal to exit out. My guess is that the invalid argument cause an error in the python code, and python errors will cause the terminal to shut down. As we see with custom mods, if there's an error in the python code the terminal wouldn't run. For example, if we filelist a non-existent directory, or not putting a directory, the terminal will exit out. Or if we put "create" and "startapp" by themselves w/o an argument, the terminal will exit out. ![image](https://user-images.githubusercontent.com/141180230/262206581-a33c850e-2665-4c86-be3c-cef4a4990003.png)

can you elaborate, like does it exit out when the custom commands have an argument but isn't entered, like how does it work?

**Comment by MultiOSDev** [comment]
> The "end" and "kill" command are buggy, and if you put end or kill and a letter between a-y, it would destroy your computer. I tested this on my linux vm and it the vm blacked out and restarted. (I'm afraid to test this on my windows computer) For example, type "end a" or "kill y" and enter

so just to confirm, it basically ends the system? i have an idea how to fix this but I need more info
