### ISSUE TITLE
Filecopy Command

### ISSUE THREAD

**Issue by RHaroldZ** [EverestWorks/EverTerm#4]
The file copy command will cause the terminal to exit out if any of the two arguments provided is invalid. It wouldn't exit out if you provide 1 or 0 argument. 
If I write "filecopy a b" while a and b are not real file/directory names, the terminal will exit out.

**Comment by MultiOSDev** [comment]
fixed issue with https://github.com/EverestWorks/EverTerm/commit/ac3500bc89da0e746efdfa6024f967d4609f46f9
